# Generated by Django 2.2.7 on 2019-11-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('res_image', models.ImageField(default='out/output.jpg', upload_to='')),
            ],
        ),
    ]
